pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            environment {
                GOPATH = "${WORKSPACE}/.gopath"
                GOMODCACHE = "${WORKSPACE}/.gopath/pkg/mod"
                GOCACHE = "${WORKSPACE}/.cache/go-build"
                HOME = "${WORKSPACE}"
            }
            steps {
                sh 'mkdir -p "$GOCACHE" "$GOMODCACHE" "$GOPATH"'
                sh 'echo "Running unit tests for backend..."'
                dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                }
            }
            post {
                always {
                    junit 'bugtracker-backend/test-results.xml'
                }
            }
        }
        stage('Unit Tests - Frontend') {
            agent {
                docker {
                    image 'node:20-alpine'
                    reuseNode true
                }
            }
            environment {
                HOME = "${WORKSPACE}"
            }
            steps {
                sh 'echo "Running unit tests for frontend..."'
                dir('bugtracker-frontend') {
                    sh '''
                    npm ci
                    npm test
                    '''
                }
            }
            post {
                always {
                    junit 'bugtracker-frontend/test-results.xml'
                }
            }
    }
}
}
